scheduling/urls.py
from django.utils import timezone
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.shortcuts import redirect
from accounts.models import User, InvitedTeacher
from school.models import Term

def home(request):
    def current_term():
        now_year = timezone.now().year
        qs = Term.objects.filter(start__year=now_year)
        if qs:
            return qs.get()
        return None

    def current_week():
        return Term.get_current_week()

    if request.user.is_authenticated:
        semester = current_term()
        if semester is None:
            return redirect(reverse_lazy('school:manage_semester', kwargs={'school_id':request.user.school.id}))
        else:
            if request.user.user_type is User.HOMEROOM:
                return redirect(reverse_lazy('timetable:home_view', kwargs={'user_id':request.user.id, 'semester_id':current_term().pk, 'start':current_week()[0]}))
            elif request.user.user_type is User.SUBJECT:
                return redirect(reverse_lazy('timetable:sub_view', kwargs={'user_id':request.user.id, 'semester_id':current_term().pk, 'start':current_week()[0]}))
            elif request.user.user_type is User.INVITED:
                semester = current_term()
                if semester is None:
                    week = current_week()
                else:
                    week = semester.get_week(InvitedTeacher.get_from(request.user).start)
                return redirect(reverse_lazy('timetable:inv_view', kwargs={'user_id':request.user.id, 'semester_id':current_term().pk, 'start':week[0]}))
    else:
        return redirect(reverse_lazy('account:login'))

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('account/', include('accounts.urls')),
    path('school/', include('school.urls')),
    path('timetable/', include('timetable.urls')),
]

school/urls.py
'''
School Information managemenet urls
'''
from django.urls import path
from . import views

app_name = 'school'

urlpatterns = [
    path('school/', views.SchoolSignUp.as_view(), name='school_signup'),
    path('<int:school_id>/manage/term', views.TermManageListView.as_view(), name='manage_semester'),
    path('<int:school_id>/manage/subject', views.SubjectManageListView.as_view(), name='manage_subject'),
    path('<int:school_id>/manage/classroom', views.ClassRoomManageListView.as_view(), name='manage_classroom'),

    path('<int:school_id>/filter_by_grade_cla/', views.ClassRoomGradeFilterView.as_view(), name='filter_classroom'),
    path('<int:school_id>/filter_by_grade_sub/', views.SubjectGradeFilterView.as_view(), name='filter_subject'),

    path('semesters/', views.semesters, name='semesters'),
    path('<int:school_id>/create_semester/', views.SemesterCreateView.as_view(), name='create_semester'),
    path('<int:school_id>/update_semester/<int:pk>', views.SemesterUpdateView.as_view(), name='update_semester'),
    path('<int:school_id>/delete_semester/<int:pk>', views.SemesterDeleteView.as_view(), name='delete_semester'),

    path('holidays/', views.holidays, name='holidays'),
    path('<int:school_id>/create_holiday/', views.HolidayCreateView.as_view(), name='create_holiday'),
    path('<int:school_id>/update_holiday/<int:pk>', views.HolidayUpdateView.as_view(), name='update_holiday'),
    path('<int:school_id>/delete_holiday/<int:pk>', views.HolidayDeleteView.as_view(), name='delete_holiday'),

    path('classrooms/', views.classrooms, name='classrooms'),
    path('<int:school_id>/create_classroom/', views.ClassRoomCreateView.as_view(), name='create_classroom'),
    path('<int:school_id>/update_classroom/<int:pk>', views.ClassRoomUpdateView.as_view(), name='update_classroom'),
    path('<int:school_id>/delete_classroom/<int:pk>', views.ClassRoomDeleteView.as_view(), name='delete_classroom'),

    path('subjects/', views.subjects, name='subjects'),
    path('<int:semester_id>/create_subject/', views.SubjectCreateView.as_view(), name='create_subject'),
    path('<int:semester_id>/update_subject/<int:pk>', views.SubjectUpdateView.as_view(), name='update_subject'),
    path('<int:semester_id>/delete_subject/<int:pk>', views.SubjectDeleteView.as_view(), name='delete_subject'),
]

timetable/urls.py
'''
modul doc
'''
from django.urls import path, register_converter
from . import converters, views

register_converter(converters.DateConverter, 'date')

app_name = 'timetable'

urlpatterns = [
    path('<int:user_id>/<int:semester_id>/sub/create/', views.SubjectCreate.as_view(), name='sub_create'),
    path('<int:user_id>/<int:semester_id>/sub/reset/', views.SubjectReset.as_view(), name='sub_reset'),
    path('<int:user_id>/<int:semester_id>/<date:start>/sub/view/', views.SubjectView.as_view(), name='sub_view'),
    path('<int:user_id>/<int:semester_id>/<date:start>/sub/update/', views.SubjectUpdate.as_view(), name='sub_update'),

    path('<int:user_id>/<int:semester_id>/home/create/', views.HomeroomCreate.as_view(), name='home_create'),
    path('<int:user_id>/<int:semester_id>/home/reset/', views.HomeroomReset.as_view(), name='home_reset'),
    path('<int:user_id>/<int:semester_id>/<date:start>/home/view/', views.HomeroomView.as_view(), name='home_view'),
    path('<int:user_id>/<int:semester_id>/<date:start>/home/update/', views.HomeroomUpdate.as_view(), name='home_update'),

    path('<int:user_id>/<int:semester_id>/inv/create/', views.InvitedCreate.as_view(), name='inv_create'),
    path('<int:user_id>/<int:semester_id>/inv/reset/', views.InvitedReset.as_view(), name='inv_reset'),
    path('<int:user_id>/<int:semester_id>/<date:start>/inv/view/', views.InvitedView.as_view(), name='inv_view'),
    path('<int:user_id>/<int:semester_id>/<date:start>/inv/update/', views.InvitedUpdate.as_view(), name='inv_update'),
]

timetable/views.py
"""
module doc
"""
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages
from django.shortcuts import redirect
from django.views import generic
from django.urls import reverse_lazy
from bootstrap_modal_forms.generic import BSModalFormView
from school.models import Term, Subject, ClassRoom
from .models import SubjectTable, HomeTable, Invited
from .forms import TableCreateForm
from .forms import (SubjectTableForm, HomeTableForm, InvitedTableForm, SubjectTableUpdateFormset, HomeTableUpdateFormset, InvitedTableUpdateFormset)
from .utils import create_list_for_weeks
##########################################################
### Teacher Roles == Subject Features
class SubjectCreate(LoginRequiredMixin, BSModalFormView):
    '''
    class doc
    '''
    form_class = TableCreateForm
    template_name = 'create.html'

    # added member
    def get_semester(self):
        qs = Term.objects.filter(pk=self.kwargs['semester_id']) # in url
        if qs:
            return qs.get()
        return None

    def form_valid(self, form):
        if self.request.is_ajax(): #bug django-bootstrap-modal-forms twice redirection
            semester = form.cleaned_data['semester']
            week = semester.get_week()
            weeks = semester.get_count_of_weeks()
            bulk_tables = []
            for i in range(0, weeks+1):
                for j in range(0, 40):
                    new_table = SubjectTable(teacher=self.request.user, semester=semester, day=week[j%5] + timezone.timedelta(days=7*i), time=(j//5)%8+1)
                    bulk_tables.append(new_table)
            SubjectTable.objects.bulk_create(bulk_tables)
        return redirect(self.get_success_url())

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

    def get_success_url(self):
        week = Term.get_current_week()
        return reverse_lazy('timetable:sub_view', kwargs={'user_id':self.request.user.id, 'semester_id':self.get_semester().pk, 'start':week[0]})

class SubjectUpdate(LoginRequiredMixin, generic.UpdateView):
    '''
    class doc
    '''
    template_name = 'sub/update.html'
    model = SubjectTable
    form_class = SubjectTableForm

    # added member
    def get_semester(self):
        qs = Term.objects.filter()
        if qs:
            return qs.get()
        return None

    def create_list_for_weeks(self):
        return create_list_for_weeks(self.get_semester())

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy('timetable:sub_view', kwargs={'user_id':self.request.user.id, 'semester_id':self.kwargs['semester_id'], 'start':self.kwargs['start']})

    def get_context_data(self, **kwargs):
        context = super(SubjectUpdate, self).get_context_data(**kwargs)
        start = self.kwargs['start']
        end = start + timezone.timedelta(days=4)
        qs = SubjectTable.objects.filter(semester=self.get_semester(), teacher=self.request.user, day__range=(start, end)).order_by("time", "day")
        if self.request.POST:
            context['timetables'] = SubjectTableUpdateFormset(self.request.POST, instance=self.request.user, queryset=qs)
        else:
            context['timetables'] = SubjectTableUpdateFormset(instance=self.request.user, queryset=qs)
        context['list_weeks'] = self.create_list_for_weeks()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['timetables']
        if formset.is_valid():
            weeks = []
            for week in context['list_weeks']:
                if self.request.POST.get(f"{week['day'].strftime('%W')}week") is not None:
                    weeks.append(self.request.POST.get(f"{week['day'].strftime('%W')}week"))
            for form in formset:
                inst = form.save(commit=False)
                qs = SubjectTable.objects.filter(semester=Term.get_current(), teacher=self.request.user, day__iso_week_day=inst.day.isoweekday(), day__week__in=weeks, time=inst.time)
                for ins in qs:
                    ins.subject = inst.subject
                    ins.classroom = inst.classroom
                    ins.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

class SubjectReset(LoginRequiredMixin, BSModalFormView):
    form_class = TableCreateForm
    template_name = 'reset.html'

    def form_valid(self, form):
        if self.request.is_ajax(): #bug django-bootstrap-modal-forms twice redirection
            semester = form.cleaned_data['semester']
            sub = SubjectTable.objects.filter(teacher=self.request.user, semester=semester)
            HomeTable.objects.filter(sub_teacher__in=sub).update(subject=None, sub_teacher=None)
            sub.update(classroom=None, subject=None)
        return redirect(self.get_success_url())

    def get_success_url(self):
        week = Term.get_current_week()
        return reverse_lazy('timetable:sub_view', kwargs={'user_id':self.request.user.id, 'semester_id':self.kwargs['semester_id'], 'start':week[0]})

class SubjectView(LoginRequiredMixin, generic.TemplateView):
    '''
    class doc
    '''
    template_name = 'sub/view.html'
    model = SubjectTable

    # added member
    def get_semester(self):
        qs = Term.objects.filter()
        if qs:
            return qs.get()
        return None

    def get_week(self):
        start = self.kwargs['start']
        end = start + timezone.timedelta(days=4)
        return {'start':self.kwargs['start'], 'end':end}

    def create_list_for_weeks(self):
        return create_list_for_weeks(self.get_semester())

    def create_information(self):
        '''
        Return TimeTable information to Templates
        '''
        information = dict()
        semester = self.get_semester()
        if semester is None:
            return
        weeks = semester.get_weeks_start_end()
        classrooms = SubjectTable.objects.exclude(classroom=None).distinct('classroom').values_list('classroom', flat=True).order_by()

        for classroom in classrooms:
            count_per_week = []
            for week in weeks:
                count_per_week.append(SubjectTable.objects.filter(semester=self.get_semester(), teacher=self.request.user, classroom=classroom, day__range=(week[0].strftime("%Y-%m-%d"), week[1].strftime("%Y-%m-%d"))).count())
            dic = {ClassRoom.objects.get(pk=classroom):[count_per_week, SubjectTable.objects.filter(teacher=self.request.user, classroom=classroom).count()]}

            information.update(dic)
        return information

    def get_success_url(self):
        '''
        class doc
        '''
        return redirect('timetable:sub_view')

    def get_context_data(self, **kwargs):
        context = super(SubjectView, self).get_context_data(**kwargs)
        start = self.kwargs['start']
        end = start + timezone.timedelta(days=4)
        context['timetables'] = SubjectTable.objects.filter(semester=self.get_semester(), teacher=self.request.user, day__range=(start, end)).order_by("time", "day")
        context['list_weeks'] = self.create_list_for_weeks()
        context['information'] = self.create_information()
        return context

### the end of subject
##########################################################
### Teacher Roles == Homeroom Features
class HomeroomCreate(LoginRequiredMixin, BSModalFormView):
    form_class = TableCreateForm
    template_name = 'create.html'

    # added member
    def get_semester(self):
        qs = Term.objects.filter(pk=self.kwargs['semester_id']) # in url
        if qs:
            return qs.get()
        return None

    def form_valid(self, form):
        if self.request.is_ajax(): #bug django-bootstrap-modal-forms twice redirection
            semester = form.cleaned_data['semester']
            week = semester.get_week()
            weeks = semester.get_count_of_weeks()
            bulk_tables = []
            for i in range(0, weeks+1):
                for j in range(0, 40):
                    classroom = self.request.user.return_by_type().classroom
                    new_table = HomeTable(semester=semester, teacher=self.request.user, classroom=classroom, day=week[j%5]+timezone.timedelta(days=7*i), time=(j//5)%8+1)
                    bulk_tables.append(new_table)
            HomeTable.objects.bulk_create(bulk_tables)
        return redirect(self.get_success_url())

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

    def get_success_url(self):
        week = Term.get_current_week()
        return reverse_lazy('timetable:home_view', kwargs={'user_id':self.request.user.id, 'semester_id':self.get_semester().pk, 'start':week[0]})

class HomeroomUpdate(LoginRequiredMixin, generic.UpdateView):
    '''
    class doc
    '''
    template_name = 'home/update.html'
    model = HomeTable
    form_class = HomeTableForm

    # added member
    def get_semester(self):
        qs = Term.objects.filter()
        if qs:
            return qs.get()
        return None

    def create_list_for_weeks(self):
        return create_list_for_weeks(self.get_semester())

    def auto_created_subject(self):
        from operator import itemgetter
        # picking algorithm
        sub_lis = []
        subjects = Subject.objects.filter(grade=self.request.user.return_by_type().get_grade())
        for subject in subjects:
            cur = HomeTable.objects.filter(subject=subject).count()
            tot = subject.count
            # caculate key value
            key = cur/tot
            sub_lis.append((key, subject))

timetable/templates/HomeRoomCreate.html
{% extends 'base.html' %}

{% block scripts %}
<script>
  $(function(){
    $('#Table-Create-Form').on('submit', function(){
      alert();
    })
  });
</script>
{% endblock %}

{% block content %}
<form action="{% url 'sub_create' user.id %}" method="post" id="Table-Create-Form">
  {% csrf_token %}
  {{ formset.management_form }}
  {{ formset.non_form_errors.as_ul }} 
 
  <h2>forms</h2>
  <table border='1' id="TimeTableCreate">
    <td align="center">월</td>
    <td align="center">화</td>
    <td align="center">수</td>
    <td align="center">목</td>
    <td align="center">금</td>
    {% for form in formset %}

    {% if forloop.first %}
      {{ form.semester }}
    {% endif %}

    {% cycle '<tr>' '' '' '' '' %}
      <td align="center">
        {{ form.classRoom }}
        {{ form.subject }}
      </td>
    {% cycle '' '' '' '' '</tr>' %}
    {% endfor %}
  </table>
  <input type="submit" class="btn btn-primary" value="Go Go Gadget &rarr;">
</form>
{% endblock %}

timetable/templates/home_create.html
{% extends 'base.html' %}

{% load widget_tweaks %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/table.css' %}">

<div class="container mt-3">
  <div class="row">
    <div class="col-10 offset-2">
      <form action="{% url 'timetable:home_create' user.id %}" method="post" id="Table-Update-form">
        {% csrf_token %}
        <h2>Homeroom</h2>
          <table class="table table-bordered table-sm" id="TimeTableUpdate">
            <thead class="thead-light">
              <th scope="col">#</th>
              <th scope="col">Mon</th>
              <th scope="col">Tue</th>
              <th scope="col">Wed</th>
              <th scope="col">Thr</th>
              <th scope="col">Fri</th>
            </thead>
            <tbody>
            {% for course in formset %}
            {% cycle '<tr scope="row"><th>1</th>' '' '' '' '' %}
              <td>  
                {% for field in course %}
                <div class="form-group">
                  <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                  {% render_field field class="form-control" placeholder=field.label %}
                  <div class="{% if field.errors %} invalid {% endif %}">
                    {% for error in field.errors %}
                      <p class="help-block">{{ error }}</p>
                    {% endfor %}
                  </div>
                </div>
                {% endfor %}
              </td>
            {% cycle '' '' '' '' '</tr>' %}
            {% endfor %}
            </tbody>
          </table>
          </div>
          {{ formset.management_form }}
          {{ formset.non_form_errors.as_ul }}
          <input type="submit" class="btn btn-primary" value="Go Go Gadget &rarr;">
      </form>
    </div>
  </div>
</div>
{% endblock content %}

timetable/templates/home_update.html
{% extends 'base.html' %}

{% load widget_tweaks %}
{% load static %}

{% block extrascripts %}
<link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css'%}"/>
<script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
<script>
$(function() {
      $('#weekpicker').datepicker({
          format: "yyyy/mm/dd",
          daysOfWeekDisabled: "0,2,3,4,5,6",
          daysOfWeekHighlighted: "1,2,3,4,5",
          calendarWeeks: true,
          showOtherMonths: true,
          selectOtherMonths: true,
          })
          .on('changeDate', function(event) { 
              var startDate = new Date($(this).val());
              var endDate = new Date();
              endDate.setDate(startDate.getDate() + 4);
              $.ajax({
                type: $(this).attr('method'),         
                url: $(this).attr('action'),
                data: { 'startdate':startDate.toISOString(), 
                        'enddate' : endDate.toISOString(),
                        'csrfmiddlewaretoken': '{{ csrf_token }}', 
                        'timetable_set-TOTAL_FORMS' : 40, // needed for formset
                        'timetable_set-INITIAL_FORMS': 40,
                        'timetable_set-MAX_NUM_FORMS' : 1000,
                      }, 
              success : function(response) {
                $('#Table-Update-form').html(response);
              },
              error : function(xhr,errmsg,err) {
                  $('#Table-Update-form').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                      " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
                  console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
              }})
          });
  });
</script>
{% endblock extrascripts %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/table.css' %}">

<div class="container mt-3">
  <div class="row">
    <div class="col-10 offset-2">
    <form action="{% url 'timetable:home_update' user.id %}" method="post" id="Table-Update-form">
    {% csrf_token %}
      <h2>Homeroom</h2>
      <div>
        <input id="weekpicker" type="text" data-provide="datepicker" class="form-control">
      </div>
        <div class="table-wrap">
        <table class="table table-bordered table-sm" id="TimeTableUpdate">
          <thead class="thead-light">
            <th scope="col">#</th>
            <th scope="col">Mon</th>
            <th scope="col">Tue</th>
            <th scope="col">Wed</th>
            <th scope="col">Thr</th>
            <th scope="col">Fri</th>
          </thead>
          <tbody>
          {% for course in TimeTables %}
          {% cycle '<tr scope="row"><th class="align-middle"> 1 </th>' '' '' '' '' %}
            <td> 
              {% for field in course %}
              <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {% render_field field class="form-control" placeholder=field.label %}
                <div class="{% if field.errors %} invalid {% endif %}">
                  {% for error in field.errors %}
                    <p class="help-block">{{ error }}</p>
                  {% endfor %}
                </div>
              </div>
              {% endfor %}
            </td>
          {% cycle '' '' '' '' '</tr>' %}
          {% endfor %}
          </tbody>
        </table>
        </div>
        {{ TimeTables.management_form }}
        {{ TimeTables.non_form_errors.as_ul }}
        <input type="submit" class="btn btn-primary" value="Go Go Gadget &rarr;">
      </form>
    </div>
  </div>
</div>
{% endblock content %}

timetable/templates/home_view.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/table.css' %}">

<div class="container mt-3">
  <div class="row">
    <div class="col-10 offset-2">
    
    <form action="{% url 'timetable:home_view' user.id %}" method="get" id="Table-View-form">
    {% csrf_token %}
      <h2>Homeroom</h2>
        <table class="table table-bordered table-hover" id="TimeTableView">
          <thead class="">
            <th scope="col">#</th> 
            <th scope="col">Mon</th>
            <th scope="col">Tue</th>
            <th scope="col">Wed</th>
            <th scope="col">Thr</th>
            <th scope="col">Fri</th>
          </thead>
          <tbody>
          {% for course in TimeTables %}
            {% cycle '<tr scope="row"><th class="align-middle">1</th>' '' '' '' '' %}
              <td class="min">
                <div class="col"> 
                  <p>{% if course.classRoom %}{{ course.classRoom }}{% endif %}</p>
                  <p>{% if course.subject %}{{ course.subject }}{% endif %}</p>
                  <p>{% if course.sub_teacher %}{{ course.sub_teacher }}{% endif %}</p>
                </div>
              </td>
            {% cycle '' '' '' '' '</tr>' %}
          {% endfor %}
          </tbody>
        </table>
        {{ TimeTables.management_form }}
        {{ TimeTables.non_form_errors.as_ul }} 
        <a href="{% url 'timetable:home_create' user.id %}">create</a>
        <a href="{% url 'timetable:home_update' user.id %}">update</a>
    </form>
   
  </div>
  </div>
</div>

  
{% if count %}
{% include '_count_subjects.html' %}
{% endif %}


{% endblock %}

timetable/templates/sub_create.html
{% extends 'base.html' %}

{% load widget_tweaks %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/table.css' %}">

<div class="container mt-3">
  <div class="row">
    <div class="col-10 offset-2">
    <form action="{% url 'timetable:sub_create' user.id %}" method="post" id="Table-Create-Form">
    {% csrf_token %}
      {{ formset.management_form }}
      {{ formset.non_form_errors.as_ul }} 
 
     <h2>Subject</h2>
      <table class="table table-bordered table-hover" id="TimeTableUpdate">
        <thead class="thead-light">
          <th scope="col">#</th>
          <th scope="col">Mon</th>
          <th scope="col">Tue</th>
          <th scope="col">Wed</th>
          <th scope="col">Thr</th>
          <th scope="col">Fri</th>
        </thead>
        <tbody>
        {% for course in formset %}
        {% cycle '<tr scope="row"><th>1</th>' '' '' '' '' %}
          <td>  
            {% for field in course %}
            <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {% render_field field class="form-control" placeholder=field.label %}
              <div class="{% if field.errors %} invalid {% endif %}">
                {% for error in field.errors %}
                  <p class="help-block">{{ error }}</p>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
          </td>
        {% cycle '' '' '' '' '</tr>' %}
        {% endfor %}
        </tbody>
      </table>
      <input type="submit" class="btn btn-primary" value="Go Go Gadget &rarr;">
    </form>
    </div>
    
  </div>
</div>
{% endblock %}

timetable/templates/sub_update.html
{% extends 'base.html' %}

{% load widget_tweaks %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/table.css' %}">

<div class="container mt-3">
  <div class="row">
    <div class="col-10 offset-2">
    <form action="{% url 'timetable:sub_update' user.id %}" method="post" id="Table-Update-form">
    <h2>Subject</h2>
      <div class="table-wrap">
      <table class="table table-bordered table-sm" id="TimeTableUpdate">
        <thead class="thead-light">
          <th scope="col">#</th>
          <th scope="col">Mon</th>
          <th scope="col">Tue</th>
          <th scope="col">Wed</th>
          <th scope="col">Thr</th>
          <th scope="col">Fri</th>
        </thead>
        <tbody>
        {% csrf_token %}
        {% for course in TimeTables %}
        {% cycle '<tr scope="row"><th> 1 </th>' '' '' '' '' %}
          <td> 
            {% for field in course %}
            <div class="form-group">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {% render_field field class="form-control" placeholder=field.label %}
              <div class="{% if field.errors %} invalid {% endif %}">
                {% for error in field.errors %}
                  <p class="help-block">{{ error }}</p>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
          </td>
        {% cycle '' '' '' '' '</tr>' %}
        {% endfor %}
        </tbody>
      </table>
      </div>
      {{ TimeTables.management_form }}
      {{ TimeTables.non_form_errors.as_ul }}
      <input type="submit" class="btn btn-primary" value="Go Go Gadget &rarr;">
    </div>
    </form>

  </div>
</div>
{% endblock content %}

timetable/templates/sub_view.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/table.css' %}">

<div class="container mt-3">
  <div class="row">
    <div class="col-10 offset-2">
    <form action="{% url 'timetable:sub_view' user.id %}" method="get" id="Table-View-form">
      {% csrf_token %}
 
      <h2>Subject</h2>
      <a href="{% url 'timetable:home_view' user.id %}">temporal</a>
      <table class="table table-bordered table-hover" id="TimeTableView">
        <thead class="">
          <th scope="col">#</th> 
          <th scope="col">Mon</th>
          <th scope="col">Tue</th>
          <th scope="col">Wed</th>
          <th scope="col">Thr</th>
          <th scope="col">Fri</th>
        </thead>
        <tbody>
        {% for course in TimeTables %}
        {% cycle '<tr scope="row"><th>1</th>' '' '' '' '' %}
          <td>
              <div class="col"> 
                <div class="col"> 
                  {% if course.classroom %}{{ course.classroom }}{% endif %}
                </div>
                <p>{% if course.subject %}{{ course.subject }}{% endif %}</p>
            </div>
          </td>
        {% cycle '' '' '' '' '</tr>' %}
        {% endfor %}
        </tbody>
        </table>
      {{ TimeTables.management_form }}
      {{ TimeTables.non_form_errors.as_ul }} 
      <a href="{% url 'timetable:sub_create' user.id %}">create</a>
      <a href="{% url 'timetable:sub_update' user.id %}">update</a>
    </form>
    </div>
    
  </div>
</div>
{% endblock %}