scheduling/urls.py
from django.utils import timezone
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.shortcuts import redirect
from accounts.models import User, InvitedTeacher
from school.models import Term

def home(request):
    def current_term():
        now_year = timezone.now().year
        qs = Term.objects.filter(start__year=now_year)
        if qs:
            return qs.get()
        return None

    def current_week():
        return Term.get_current_week()

    if request.user.is_authenticated:
        semester = current_term()
        if semester is None:
            return redirect(reverse_lazy('school:manage_semester', kwargs={'school_id':request.user.school.id}))
        else:
            if request.user.user_type is User.HOMEROOM:
                return redirect(reverse_lazy('timetable:home_view', kwargs={'user_id':request.user.id, 'semester_id':current_term().pk, 'start':current_week()[0]}))
            elif request.user.user_type is User.SUBJECT:
                return redirect(reverse_lazy('timetable:sub_view', kwargs={'user_id':request.user.id, 'semester_id':current_term().pk, 'start':current_week()[0]}))
            elif request.user.user_type is User.INVITED:
                semester = current_term()
                if semester is None:
                    week = current_week()
                else:
                    week = semester.get_week(InvitedTeacher.get_from(request.user).start)
                return redirect(reverse_lazy('timetable:inv_view', kwargs={'user_id':request.user.id, 'semester_id':current_term().pk, 'start':week[0]}))
    else:
        return redirect(reverse_lazy('account:login'))

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('account/', include('accounts.urls')),
    path('school/', include('school.urls')),
    path('timetable/', include('timetable.urls')),
]

school/urls.py
'''
School Information managemenet urls
'''
from django.urls import path
from . import views

app_name = 'school'

urlpatterns = [
    path('school/', views.SchoolSignUp.as_view(), name='school_signup'),
    path('<int:school_id>/manage/term', views.TermManageListView.as_view(), name='manage_semester'),
    path('<int:school_id>/manage/subject', views.SubjectManageListView.as_view(), name='manage_subject'),
    path('<int:school_id>/manage/classroom', views.ClassRoomManageListView.as_view(), name='manage_classroom'),

    path('<int:school_id>/filter_by_grade_cla/', views.ClassRoomGradeFilterView.as_view(), name='filter_classroom'),
    path('<int:school_id>/filter_by_grade_sub/', views.SubjectGradeFilterView.as_view(), name='filter_subject'),

    path('semesters/', views.semesters, name='semesters'),
    path('<int:school_id>/create_semester/', views.SemesterCreateView.as_view(), name='create_semester'),
    path('<int:school_id>/update_semester/<int:pk>', views.SemesterUpdateView.as_view(), name='update_semester'),
    path('<int:school_id>/delete_semester/<int:pk>', views.SemesterDeleteView.as_view(), name='delete_semester'),

    path('holidays/', views.holidays, name='holidays'),
    path('<int:school_id>/create_holiday/', views.HolidayCreateView.as_view(), name='create_holiday'),
    path('<int:school_id>/update_holiday/<int:pk>', views.HolidayUpdateView.as_view(), name='update_holiday'),
    path('<int:school_id>/delete_holiday/<int:pk>', views.HolidayDeleteView.as_view(), name='delete_holiday'),

    path('classrooms/', views.classrooms, name='classrooms'),
    path('<int:school_id>/create_classroom/', views.ClassRoomCreateView.as_view(), name='create_classroom'),
    path('<int:school_id>/update_classroom/<int:pk>', views.ClassRoomUpdateView.as_view(), name='update_classroom'),
    path('<int:school_id>/delete_classroom/<int:pk>', views.ClassRoomDeleteView.as_view(), name='delete_classroom'),

    path('subjects/', views.subjects, name='subjects'),
    path('<int:semester_id>/create_subject/', views.SubjectCreateView.as_view(), name='create_subject'),
    path('<int:semester_id>/update_subject/<int:pk>', views.SubjectUpdateView.as_view(), name='update_subject'),
    path('<int:semester_id>/delete_subject/<int:pk>', views.SubjectDeleteView.as_view(), name='delete_subject'),
]

school/forms.py
'''
School Information Form
'''
from django import forms
from bootstrap_modal_forms.forms import BSModalModelForm, BSModalForm
from accounts.models import User
from .models import School, Term, Holiday, ClassRoom, Subject

class SchoolModelForm(BSModalModelForm):
    class Meta:
        model = School
        fields = '__all__'

class TermModelForm(BSModalModelForm):
    class Meta:
        model = Term
        fields = ['start', 'end', 'semester']

class HolidayModelForm(BSModalModelForm):
    class Meta:
        model = Holiday
        fields = ['day', 'text']
        widgets = {
            'day': forms.DateInput()
        }

class GradeFilterForm(BSModalForm):
    grade = forms.ChoiceField(choices=ClassRoom.GRADE_RANGE)

    class Meta:
        fields = ['grade', 'clear']

class ClassRoomModelForm(BSModalModelForm):
    teacher = forms.ModelChoiceField(User.objects.filter(user_type=User.HOMEROOM))

    class Meta:
        model = ClassRoom
        fields = '__all__'

class SubjectModelForm(BSModalModelForm):
    class Meta:
        model = Subject
        fields = '__all__'

school/views.py
'''
module doc
'''
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic
from bootstrap_modal_forms.generic import (
    BSModalFormView,
    BSModalCreateView,
    BSModalUpdateView,
    BSModalDeleteView
)
from .models import Term, Holiday, ClassRoom, Subject
from .forms import (
    SchoolModelForm,
    GradeFilterForm,
    TermModelForm,
    HolidayModelForm,
    ClassRoomModelForm,
    SubjectModelForm,
    )

########################################################
### management views
class SchoolSignUp(BSModalCreateView):
    '''
    inherited
    '''
    form_class = SchoolModelForm
    template_name = 'school/create.html'
    success_url = reverse_lazy('account:login')

class TermManageListView(LoginRequiredMixin, generic.ListView):
    '''
    module doc
    '''
    context_object_name = 'subjects'
    template_name = 'manage_semester.html'

    def get_queryset(self):
        return Term.objects.order_by()

    def get_context_data(self, **kwargs):
        context = super(TermManageListView, self).get_context_data()
        qs_t = Term.objects.filter(school=self.request.user.school)
        qs_h = Holiday.objects.filter(school=self.request.user.school)
        context.update({
            'semesters' : qs_t,
            'holidays' : qs_h,
        })
        return context

class SubjectManageListView(LoginRequiredMixin, generic.ListView):
    '''
    module doc
    '''
    context_object_name = 'subjects'
    template_name = 'manage_subject.html'

    def get_queryset(self):
        return Subject.objects.order_by('grade')

    def get_context_data(self, **kwargs):
        context = super(SubjectManageListView, self).get_context_data()
        qs_s = Subject.objects.filter(school=self.request.user.school)
        if 'grade' in self.request.GET:
            qs_s = qs_s.filter(grade=int(self.request.GET['grade']))
        context.update({
            'subjects' : qs_s,
        })
        return context

class ClassRoomManageListView(LoginRequiredMixin, generic.ListView):
    '''
    module doc
    '''
    context_object_name = 'subjects'
    template_name = 'manage_classroom.html'

    def get_queryset(self):
        return ClassRoom.objects.order_by('grade')

    def get_context_data(self, **kwargs):
        context = super(ClassRoomManageListView, self).get_context_data()
        qs_c = ClassRoom.objects.filter(school=self.request.user.school)
        if 'grade' in self.request.GET:
            qs_c = qs_c.filter(grade=int(self.request.GET['grade']))
        context.update({
            'classrooms' : qs_c,
        })
        return context

class ClassRoomGradeFilterView(BSModalFormView):
    '''
    module doc
    '''
    template_name = 'classroom/filter.html'
    form_class = GradeFilterForm

    def form_valid(self, form):
        if 'clear' in self.request.POST:
            self.filter = ''
        else:
            self.filter = '?grade=' + form.cleaned_data['grade']

        response = super().form_valid(form)
        return response

    def get_success_url(self):
        return reverse_lazy('school:manage_classroom') + self.filter

class SubjectGradeFilterView(BSModalFormView):
    '''
    module doc
    '''
    template_name = 'subject/filter.html'
    form_class = GradeFilterForm

    def form_valid(self, form):
        if 'clear' in self.request.POST:
            self.filter = ''
        else:
            self.filter = '?grade=' + form.cleaned_data['grade']

        response = super().form_valid(form)
        return response

    def get_success_url(self):
        return reverse_lazy('school:manage_subject') + self.filter

### the end of management feautures
########################################################
########################################################
### Holiday Features

class SemesterCreateView(BSModalCreateView):
    '''
    module doc
    '''
    template_name = "semester/create.html"
    form_class = TermModelForm
    success_message = 'Success: Semester was added.'

    def get_success_url(self):
        return reverse_lazy('school:manage_semester', kwargs={'school_id':self.request.user.school.pk})

    def form_valid(self, form):
        if self.request.is_ajax():
            instance = form.save(commit=False)
            instance.school = self.request.user.school
            instance.save()
        return redirect(self.get_success_url())

class SemesterUpdateView(BSModalUpdateView):
    '''
    module doc
    '''
    model = Term
    template_name = 'semester/update.html'
    form_class = TermModelForm

    def get_success_url(self):
        return reverse_lazy('school:manage_semester', kwargs={'school_id':self.request.user.school.pk})

class SemesterDeleteView(BSModalDeleteView):
    '''
    module doc
    '''
    model = Term
    template_name = 'semester/delete.html'
    success_message = 'Success: Semester was deleted.'

    def get_success_url(self):
        return reverse_lazy('school:manage_semester', kwargs={'school_id':self.request.user.school.pk})

def semesters(request):
    '''
    module doc
    '''
    data = dict()
    if request.method == 'GET':
        term = Term.objects.filter(school=request.user.school.pk)
        data['table'] = render_to_string(
            'semester/_table.html',
            {'semesters': term},
            request=request
        )
        return JsonResponse(data)

### the end of subject feautures
########################################################
########################################################
### Holiday Features

class HolidayCreateView(BSModalCreateView):
    '''
    module doc
    '''
    template_name = "holiday/create.html"
    form_class = HolidayModelForm
    success_message = 'Success: Holiday was added.'

    def get_success_url(self):
        return reverse_lazy('school:manage_semester', kwargs={'school_id':self.request.user.school.pk})

    def form_valid(self, form):
        if self.request.is_ajax():
            instance = form.save(commit=False)
            instance.school = self.request.user.school
            instance.save()
        return redirect(self.get_success_url())

class HolidayUpdateView(BSModalUpdateView):
    '''
    module doc
    '''
    model = Holiday
    template_name = 'holiday/update.html'
    form_class = HolidayModelForm
    success_message = 'Success: Holiday was deleted.'

    def get_success_url(self):
        return reverse_lazy('school:manage_semester', kwargs={'school_id':self.request.user.school.pk})

class HolidayDeleteView(BSModalDeleteView):
    '''
    module doc
    '''
    model = Holiday
    template_name = 'holiday/delete.html'
    success_message = 'Success: Holiday was deleted.'

    def get_success_url(self):
        return reverse_lazy('school:manage_semester', kwargs={'school_id':self.request.user.school.pk})

def holidays(request):
    '''
    module doc
    '''
    data = dict()
    if request.method == 'GET':
        holidays = Holiday.objects.filter(school=request.user.school)
        data['table'] = render_to_string(
            'holiday/_table.html',
            {'holidays': holidays},
            request=request
        )
        return JsonResponse(data)

### the end of subject feautures
########################################################
### ClassRoom Features

class ClassRoomCreateView(BSModalCreateView):
    '''
    module doc
    '''
    template_name = "classroom/create.html"
    form_class = ClassRoomModelForm

    def get_success_url(self):
        return reverse_lazy('school:manage_classroom', kwargs={'school_id':self.request.user.school.pk})

class ClassRoomUpdateView(BSModalUpdateView):
    '''
    module doc
    '''
    model = ClassRoom
    template_name = 'classroom/update.html'
    form_class = ClassRoomModelForm

    def get_success_url(self):
        return reverse_lazy('school:manage_classroom', kwargs={'school_id':self.request.user.school.pk})

class ClassRoomDeleteView(BSModalDeleteView):
    '''
    module doc
    '''
    model = ClassRoom
    template_name = 'classroom/delete.html'
    success_message = 'Success: Book was deleted.'

    def get_success_url(self):
        return reverse_lazy('school:manage_classroom', kwargs={'school_id':self.request.user.school.pk})

def classrooms(request):
    '''
    module doc
    '''
    data = dict()
    if request.method == 'GET':
        clss = ClassRoom.objects.filter(school=request.user.school)
        data['table'] = render_to_string(
            'classroom/_table.html',
            {'classrooms': clss},
            request=request
        )
        return JsonResponse(data)

### the end of classroom feautures
########################################################
### Subject Features

class SubjectCreateView(BSModalCreateView):
    '''
    module doc
    '''
    template_name = "subject/create.html"
    form_class = SubjectModelForm

    def get_success_url(self):
        return reverse_lazy('school:manage_subject', kwargs={'school_id':self.request.user.school.pk})

class SubjectUpdateView(BSModalUpdateView):
    '''
    module doc
    '''
    model = Subject
    template_name = 'subject/update.html'
    form_class = SubjectModelForm
    form_class = SubjectModelForm

    def get_success_url(self):
        return reverse_lazy('school:manage_subject', kwargs={'school_id':self.request.user.school.pk})

class SubjectDeleteView(BSModalDeleteView):
    '''
    module doc
    '''
    model = Subject
    template_name = 'subject/delete.html'
    success_message = 'Success: Subject was deleted.'

    def get_success_url(self):
        return reverse_lazy('school:manage_subject', kwargs={'school_id':self.request.user.school.pk})

def subjects(request):
    '''
    module doc
    '''
    data = dict()
    if request.method == 'GET':

school/templates/admin_view.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-3">
        <div class="row">
            <div class="col">
                <h4>
                <strong>1. classrooms</strong>
                </h4>
                <div class="row">
                    <div class="col-12 mb-3">
                        <a href="{% url 'school:manage_school' %}"> to management </a>
                    </div>
               </div>
               <h4>
                <strong>2. confirm </strong>
                </h4>
                <div class="row">
                    <div class="col-12 mb-3">
                        <form action="." method="post">
                            {% csrf_token %}
                            <div class="{% if form.non_field_errors %}invalid{% endif %} mb-2">
                                {% for error in form.non_field_errors %}
                                  {{ error }}
                                {% endfor %}
                              </div>
                            {% for field in form %}
                                {{ field }}{{ field.error }}
                            {% endfor %}
                            <input type="submit" class="btn btn-outline-primary btn-sm" value="Go Go Gadget &rarr;">
                        </form>
                    </div>
               </div>
            </div>
        </div>
    </div>
{% endblock content %}

school/templates/manage_classroom.html
{% extends 'base.html' %}

{% block content %}
 {% include "_modal.html" %}

  <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2 font-weight-bold">학급</h1>
      <div class="btn-toolbar mb-2 mb-md-0">
        <div class="btn-group mr-2">
          <button id="create-classroom" class="btn btn-outline-secondary btn-sm" type="button" name="button">
            <span class="fa fa-plus mr-2"></span>Create
          </button>
          <button id="filter-classroom" class="bs-modal btn btn-outline-secondary btn-sm" type="button" name="button" data-form-url="{% url 'school:filter_classroom' user.school.pk %}">
            <span class="fa fa-filter mr-2"></span>Filter
          </button>
        </div>
      </div>
    </div>

        <div class="row">
          <div class="col-12 mb-3">
            {% if classrooms %}
              {% include "classroom/_table.html" %}
            {% else %}
              <p class="no-classroom text-primary">아직 추가된 반이 없습니다.</p>
            {% endif %}
          </div>
        </div>
      
    </div>
  </main>
{% endblock content %}


{% block extrascripts %}
  <script type="text/javascript">
      $(function () {
          
          $("#create-classroom").modalForm({
            formURL: "{% url 'school:create_classroom' user.school.pk %}",
            modalID: "#create-modal"
          });

          var asyncSuccessMessage = [
            "<div ",
            "style='position:fixed;top:0;z-index:10000;width:100%;border-radius:0;' ",
            "class='alert alert-icon alert-success alert-dismissible fade show mb-0' role='alert'>",
            "Success: Book was updated.",
            "<button type='button' class='close' data-dismiss='alert' aria-label='Close'>",
            "<span aria-hidden='true'>&times;</span>",
            "</button>",
            "</div>",
            "<script>",
            "$('.alert').fadeTo(6000, 4000).slideUp(500, function () {$('.alert').slideUp(500).remove();});",
            "<\/script>"
          ].join("");

          function updateClassRoomModalForm() {
            $(".update-classroom").each(function () {
              $(this).modalForm({
                formURL: $(this).data("form-url"),
                asyncUpdate: true,
                asyncSettings: {
                  closeOnSubmit: false,
                  successMessage: asyncSuccessMessage,
                  dataUrl:"{% url 'school:classrooms' %}",
                  dataElementId: "#classroom-table",
                  dataKey: "table",
                  addModalFormFunction: updateClassRoomModalForm
                }
              });
            });
          }
          updateClassRoomModalForm();

          // Read and Delete book buttons open modal with id="modal"
          // The formURL is retrieved from the data of the element
          $(".bs-modal").each(function () {
              $(this).modalForm({formURL: $(this).data("form-url")});
          });

          // Hide message
          $(".alert").fadeTo(6000, 4000).slideUp(500, function () {
              $(".alert").slideUp(500);
          });
      });
  </script>
{% endblock extrascripts %}

school/templates/manage_school.html
{% extends 'base.html' %}

{% block content %}

  {% include "_modal.html" %}

  <div class="container mt-3">
    <div class="row">
      <div class="col">
        <p class="text-primary">Management</p>
        <h4>
          <strong>1. Semester</strong>
        </h4>
        <div class="row">
          <div class="col-12 mb-3">
            <button id="add-semester" class="btn btn-outline-primary btn-sm" type="button" name="button">
              <span class="fa fa-plus mr-2"></span>Add Semester
            </button>
          </div>
          <div class="col-12 mb-3">
            {% if semester %}
              {% include "semester/_table.html" %}
            {% else %}
              <p class="no-semester text-primary">No semester added yet.</p>
            {% endif %}
          </div>
        </div>
        <h4>
          <strong>2. Holidays in this Semester</strong>
        </h4>

        <div class="row">
          <div class="col-12 mb-3">
            <button id="add-holiday" class="btn btn-outline-primary btn-sm" type="button" name="button">
              <span class="fa fa-plus mr-2"></span>Add Holidays
            </button>
          </div>
          <div class="col-12 mb-3">
            {% if holidays %}
              {% include "holiday/_table.html" %}
            {% else %}
              <p class="no-holidays text-primary">No holidays added yet.</p>
            {% endif %}
          </div>
        </div>

        <h4>
          <strong>3. ClassRoom</strong>
        </h4>

        <div class="row">
          <div class="col-12 mb-3">
            <button id="create-classroom" class="btn btn-outline-primary btn-sm" type="button" name="button">
              <span class="fa fa-plus mr-2"></span>Create ClassRoom
            </button>
            <button id="filter-book" class="bs-modal btn btn-outline-primary btn-sm" type="button" name="button" data-form-url="{% url 'school:filter_classroom' %}">
              <span class="fa fa-filter mr-2"></span>Filter by Grade
            </button>
          </div>
          <div class="col-12 mb-3">
            {% if classrooms %}
              {% include "classroom/_table.html" %}
            {% else %}
              <p class="no-classroom text-primary">No classroom added yet.</p>
            {% endif %}
          </div>
        </div>

        <h4>
          <strong>4. Subject</strong>
        </h4>

        <div class="row">
          <div class="col-12 mb-3">
            <button id="create-subject" class="btn btn btn-outline-primary btn-sm" type="button" name="button">
              <span class="fa fa-plus mr-2"></span>Create Subject
            </button>
          </div>
          <div class="col-12 mb-3">
            {% if subjects %}
              {% include "subject/_table.html" %}
            {% else %}
              <p class="no-subjects text-primary">No subjects added yet.</p>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

{% block extrascripts %}
  <script type="text/javascript">
      $(function () {
          // Log in & Sign up buttons
          // The formURL is given explicitly
          // Create book button opens modal with id="create-modal"
          $("#add-semester").modalForm({
            formURL: "{% url 'school:create_semester' %}",
            modalID: "#create-modal"
          });

          $("#add-holiday").modalForm({
            formURL: "{% url 'school:create_holiday' %}",
            modalID: "#create-modal"
          });
          
          $("#create-classroom").modalForm({
            formURL: "{% url 'school:create_classroom' %}",
            modalID: "#create-modal"
          });

          $("#create-subject").modalForm({
            formURL: "{% url 'school:create_subject' %}",
            modalID: "#create-modal"
          });
          
          var asyncSuccessMessage = [
            "<div ",
            "style='position:fixed;top:0;z-index:10000;width:100%;border-radius:0;' ",
            "class='alert alert-icon alert-success alert-dismissible fade show mb-0' role='alert'>",
            "Success: Book was updated.",
            "<button type='button' class='close' data-dismiss='alert' aria-label='Close'>",
            "<span aria-hidden='true'>&times;</span>",
            "</button>",
            "</div>",
            "<script>",
            "$('.alert').fadeTo(2000, 500).slideUp(500, function () {$('.alert').slideUp(500).remove();});",
            "<\/script>"
          ].join("");

          function updateClassRoomModalForm() {
            $(".update-classroom").each(function () {
              $(this).modalForm({
                formURL: $(this).data("form-url"),
                asyncUpdate: true,
                asyncSettings: {
                  closeOnSubmit: false,
                  successMessage: asyncSuccessMessage,
                  dataUrl:"{% url 'school:classrooms' %}",
                  dataElementId: "#classroom-table",
                  dataKey: "table",
                  addModalFormFunction: updateClassRoomModalForm
                }
              });
            });
          }
          updateClassRoomModalForm();

          // Read and Delete book buttons open modal with id="modal"
          // The formURL is retrieved from the data of the element
          $(".bs-modal").each(function () {
              $(this).modalForm({formURL: $(this).data("form-url")});
          });

          // Hide message
          $(".alert").fadeTo(2000, 500).slideUp(500, function () {
              $(".alert").slideUp(500);
          });
      });
  </script>
{% endblock extrascripts %}

school/templates/manage_semester.html
{% extends 'base.html' %}

{% block content %}

  {% include "_modal.html" %}

  <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2 font-weight-bold">학기</h1>
      <div class="btn-toolbar mb-2 mb-md-0">
        <button id="add-semester" class="btn btn-outline-secondary btn-sm" type="button" name="button">
          <span class="fa fa-plus mr-2"></span>Create
        </button>
      </div>
    </div>

        <div class="row">
          <div class="col-12 mb-3">
            {% if semesters %}
              {% include "semester/_table.html" %}
            {% else %}
              <p class="no-semester text-primary">아직 생성된 학기가 없습니다.</p>
            {% endif %}
          </div>
        </div>
        
        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
          <h1 class="h2 font-weight-bold">학기 중 수업없는 날</h1>
            <div class="btn-toolbar mb-2 mb-md-0">
              <button id="add-holiday" class="btn btn-outline-secondary btn-sm" type="button" name="button">
                <span class="fa fa-plus mr-2"></span>Create
              </button>
            </div>
          </div>
          
        <div class="row">
          <div class="col-12 mb-3">
            {% if holidays %}
              {% include "holiday/_table.html" %}
            {% else %}
              <p class="no-holidays text-primary">아직 추가된 휴일이 없습니다.</p>
            {% endif %}
          </div>
        </div>

    </div>
  </main>
{% endblock content %}

{% block extrascripts %}
  <script type="text/javascript">
      $(function () {
          // Log in & Sign up buttons
          // The formURL is given explicitly
          // Create book button opens modal with id="create-modal"
          $("#add-semester").modalForm({
            formURL: "{% url 'school:create_semester' user.school.pk %}",
            modalID: "#create-modal"
          });

          $("#add-holiday").modalForm({
            formURL: "{% url 'school:create_holiday' user.school.pk %}",
            modalID: "#create-modal"
          });
          
          var asyncSuccessMessage = [
            "<div ",
            "style='position:fixed;top:0;z-index:10000;width:100%;border-radius:0;' ",
            "class='alert alert-icon alert-success alert-dismissible fade show mb-0' role='alert'>",
            "Success: Book was updated.",
            "<button type='button' class='close' data-dismiss='alert' aria-label='Close'>",
            "<span aria-hidden='true'>&times;</span>",
            "</button>",
            "</div>",
            "<script>",
            "$('.alert').fadeTo(2000, 500).slideUp(500, function () {$('.alert').slideUp(500).remove();});",
            "<\/script>"
          ].join("");

          function updateSemesterModalForm() {
            $(".update-semester").each(function () {
              $(this).modalForm({
                formURL: $(this).data("form-url"),
                asyncUpdate: true,
                asyncSettings: {
                  closeOnSubmit: false,
                  successMessage: asyncSuccessMessage,
                  dataUrl:"{% url 'school:semesters' %}",
                  dataElementId: "#semester-table",
                  dataKey: "table",
                  addModalFormFunction: updateSemesterModalForm
                }
              });
            });
          }
          updateSemesterModalForm();

          function updateHolidayModalForm() {
            $(".update-holiday").each(function () {
              $(this).modalForm({
                formURL: $(this).data("form-url"),
                asyncUpdate: true,
                asyncSettings: {
                  closeOnSubmit: false,
                  successMessage: asyncSuccessMessage,
                  dataUrl:"{% url 'school:holidays' %}",
                  dataElementId: "#holiday-table",
                  dataKey: "table",
                  addModalFormFunction: updateHolidayModalForm
                }
              });
            });
          }
          updateHolidayModalForm();

          // Read and Delete book buttons open modal with id="modal"
          // The formURL is retrieved from the data of the element
          $(".bs-modal").each(function () {
              $(this).modalForm({formURL: $(this).data("form-url")});
          });

          // Hide message
          $(".alert").fadeTo(2000, 500).slideUp(500, function () {
              $(".alert").slideUp(500);
          });
      });
  </script>
{% endblock extrascripts %}