accounts/urls.py
'''
doc
'''
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/home/', views.HomeroomSignUpView.as_view(), name='homeroom_signup'),
    path('signup/sub/', views.SubjectSignUpView.as_view(), name='subject_signup'),
    path('signup/inv/', views.InvitedSignUpView.as_view(), name='invited_signup'),
    
    path('<int:user_id>/profile/', views.profileView, name='profile_view'),
    path('<int:user_id>/profile/update/home', views.homeroomProfileUpdate, name='home_profile'),
    path('<int:user_id>/profile/update/sub', views.subjectProfileView, name='sub_profile'),
    path('<int:user_id>/profile/update/inv', views.invitedProfileView, name='inv_profile'),

]

scheduling/urls.py
from django.utils import timezone
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.shortcuts import redirect
from accounts.models import User, InvitedTeacher
from school.models import Term

def home(request):
    def current_term():
        now_year = timezone.now().year
        qs = Term.objects.filter(start__year=now_year)
        if qs:
            return qs.get()
        return None

    def current_week():
        return Term.get_current_week()

    if request.user.is_authenticated:
        semester = current_term()
        if semester is None:
            return redirect(reverse_lazy('school:manage_semester', kwargs={'school_id':request.user.school.id}))
        else:
            if request.user.user_type is User.HOMEROOM:
                return redirect(reverse_lazy('timetable:home_view', kwargs={'user_id':request.user.id, 'semester_id':current_term().pk, 'start':current_week()[0]}))
            elif request.user.user_type is User.SUBJECT:
                return redirect(reverse_lazy('timetable:sub_view', kwargs={'user_id':request.user.id, 'semester_id':current_term().pk, 'start':current_week()[0]}))
            elif request.user.user_type is User.INVITED:
                semester = current_term()
                if semester is None:
                    week = current_week()
                else:
                    week = semester.get_week(InvitedTeacher.get_from(request.user).start)
                return redirect(reverse_lazy('timetable:inv_view', kwargs={'user_id':request.user.id, 'semester_id':current_term().pk, 'start':week[0]}))
    else:
        return redirect(reverse_lazy('account:login'))

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('account/', include('accounts.urls')),
    path('school/', include('school.urls')),
    path('timetable/', include('timetable.urls')),
]

school/urls.py
'''
School Information managemenet urls
'''
from django.urls import path
from . import views

app_name = 'school'

urlpatterns = [
    path('school/', views.SchoolSignUp.as_view(), name='school_signup'),
    path('<int:school_id>/manage/term', views.TermManageListView.as_view(), name='manage_semester'),
    path('<int:school_id>/manage/subject', views.SubjectManageListView.as_view(), name='manage_subject'),
    path('<int:school_id>/manage/classroom', views.ClassRoomManageListView.as_view(), name='manage_classroom'),

    path('<int:school_id>/filter_by_grade_cla/', views.ClassRoomGradeFilterView.as_view(), name='filter_classroom'),
    path('<int:school_id>/filter_by_grade_sub/', views.SubjectGradeFilterView.as_view(), name='filter_subject'),

    path('semesters/', views.semesters, name='semesters'),
    path('<int:school_id>/create_semester/', views.SemesterCreateView.as_view(), name='create_semester'),
    path('<int:school_id>/update_semester/<int:pk>', views.SemesterUpdateView.as_view(), name='update_semester'),
    path('<int:school_id>/delete_semester/<int:pk>', views.SemesterDeleteView.as_view(), name='delete_semester'),

    path('holidays/', views.holidays, name='holidays'),
    path('<int:school_id>/create_holiday/', views.HolidayCreateView.as_view(), name='create_holiday'),
    path('<int:school_id>/update_holiday/<int:pk>', views.HolidayUpdateView.as_view(), name='update_holiday'),
    path('<int:school_id>/delete_holiday/<int:pk>', views.HolidayDeleteView.as_view(), name='delete_holiday'),

    path('classrooms/', views.classrooms, name='classrooms'),
    path('<int:school_id>/create_classroom/', views.ClassRoomCreateView.as_view(), name='create_classroom'),
    path('<int:school_id>/update_classroom/<int:pk>', views.ClassRoomUpdateView.as_view(), name='update_classroom'),
    path('<int:school_id>/delete_classroom/<int:pk>', views.ClassRoomDeleteView.as_view(), name='delete_classroom'),

    path('subjects/', views.subjects, name='subjects'),
    path('<int:semester_id>/create_subject/', views.SubjectCreateView.as_view(), name='create_subject'),
    path('<int:semester_id>/update_subject/<int:pk>', views.SubjectUpdateView.as_view(), name='update_subject'),
    path('<int:semester_id>/delete_subject/<int:pk>', views.SubjectDeleteView.as_view(), name='delete_subject'),
]

scheduling/templates/_footer.html
<footer class="footer fixed-bottom" style="border-top: 1px solid #eee;">
  <div class="container">
    <span class="text-muted">maintained.by.an@gmail.com</span>
  </div>
</footer>

scheduling/templates/_header.html
{% load static %}

<!-- Header -->
<header style="border-bottom: 1px solid #eee;">
  <!-- Messages -->
  <div>
    {% if messages %}
      {% for message in messages %}
        <div style="border-radius:0;" {% if message.tags %} class="alert alert-icon alert-{{ message.tags }} alert-dismissible fade show mb-0" role="alert" {% endif %}>
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
    {% endif %}
  </div>
  <!-- End Messages -->
  {% if user.is_authenticated %}
    <!-- Navbar -->
    <!-- Important: columns can be used directly in navbar since it is d-flex -->
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark p-0 shadow">
      <a class="navbar-brand col-sm-2 col-md-2 mr-0 text-center" href="{% url 'home' %}">Scheduler</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav px-3">
          <li class="nav-item text-nowrap">
            <a class="nav-link" href="{% url 'home' %}">시간표</a>
          </li>
          <li class="nav-item text-nowrap">
            <a class="nav-link" href="{% url 'school:manage_semester' user.school.pk %}">학기관리</a>
          </li>
          {% if user.user_type == 1%}
          <li class="nav-item text-nowrap">
            <a class="nav-link" href="{% url 'school:manage_classroom' user.school.pk %}">학급관리</a>
          </li>
          {% endif %}
          {% if user.user_type == 1 or user.user_type == 2%}
          <li class="nav-item text-nowrap">
            <a class="nav-link" href="{% url 'school:manage_subject' user.school.pk  %}">교과관리</a>
          </li>
          {% endif %}
          <li class="nav-item text-nowrap">
            <a class="nav-link" href="{% url 'account:profile_view' user.id %}">개인정보</a>
          </li>
        </ul>
      
      {% if not user.is_anonymous %}
        <p class="text-muted ml-auto pl-3 m-2">
          안녕하세요 <strong>{{ user }}</strong>선생님
          <a href="{% url 'account:logout' %}" id="logout-btn" style="font-size: 80%;" role="button">로그아웃</a>
        </p>
      {% endif %}

    </div>
      
    </nav>
    <!-- End Navbar -->
    {% endif %}

</header>
<!-- End Header -->

scheduling/templates/_modal.html
<div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog mt-5">
    <div class="modal-content">
    </div>
  </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog mt-5" role="document">
    <div class="modal-content"></div>
  </div>
</div>

scheduling/templates/_sidebar.html
<div class="container">

        <div class="col-2 px-1 ml-3 position-fixed" id="sticky-sidebar">
            <div class="nav flex-column flex-nowrap vh-100 overflow-auto text-white p-2">
                <a href="{% url 'school:manage_semester' %}" class="nav-link">개인정보</a>
                <a href="{% url 'school:manage_semester' %}" class="nav-link">학기관리</a>
                <a href="{% url 'school:manage_classroom' %}" class="nav-link">반관리</a>
                <a href="{% url 'school:manage_subject' %}" class="nav-link">교과관리</a>
            </div>
        </div>
   
</div>

scheduling/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">

    {% block stylesheets %}
      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
      <!-- font-awesome CDN -->
      <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
      <!-- Custom CSS -->
      <link rel="stylesheet" href="{% static 'css/dashboard.css' %}" >
    {% endblock stylesheets %}

    <title>Scheduler</title>
  </head>

  <body>
    <!-- Includes -->
    {% include "_header.html" %}

    <div class="container-fluid">
      <div class="row">
    {% block content %}{% endblock content %}
      </div>
    </div>
    <!-- Includes -->
    <!-- {% include "_footer.html" %} -->

    <!-- JavaScript -->
    {% block scripts %}
      <script src="{% static 'assets/js/jquery-3.2.1.min.js' %}"></script>
      <script src="{% static 'assets/js/popper.min.js' %}"></script>
      <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
      <!-- You can alternatively load the minified version -->
      <script src="{% static 'js/jquery.bootstrap.modal.forms.js' %}"></script>
    {% endblock scripts %}

    {% block extrascripts %}{% endblock extrascripts %}

  </body>

</html>

scheduling/templates/home.html
{% extends 'base.html' %}

{% block scripts %}
<script type="text/javascript">
    $(document).ready(function() {
    
        $(".signup-btn").modalForm({
            formURL: "/accounts/signup/"
      });
    
    });
</script>
{% endblock %}

{% block content %}
<h2>Login</h2>
<button class="signup-btn btn btn-primary" type="button" name="button">Sign up</button>
<form action="." method="get">

    <a href="{% url 'index' %}"> accounts </a>
    <a href="{% url 'school:admin_view' %}"> manage </a>
    <a href="{% url 'timetable:sub_view' user.id %}"> subject </a>
    <a href="{% url 'timetable:home_view' user.id %}"> homeroom </a>

</form>
{% endblock %}

scheduling/templates/index.html
{% extends 'base.html' %}

{% block scripts %}
<script type="text/javascript">
    $(document).ready(function() {
    
        $(".signup-btn").modalForm({
            formURL: "/accounts/signup/"
      });
    
    });
</script>
{% endblock %}

{% block content %}
<h2>Login</h2>
<button class="signup-btn btn btn-primary" type="button" name="button">Sign up</button>
<form action="." method="get">

    <a href="{% url 'school:admin_view' %}"> manage </a>
    <a href="{% url 'timetable:sub_view' user.id %}"> subject </a>
    <a href="{% url 'timetable:home_view' user.id %}"> homeroom </a>

</form>
{% endblock %}