scheduling/urls.py
from django.utils import timezone
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.shortcuts import redirect
from accounts.models import User, InvitedTeacher
from school.models import Term

def home(request):
    def current_term():
        now_year = timezone.now().year
        qs = Term.objects.filter(start__year=now_year)
        if qs:
            return qs.get()
        return None

    def current_week():
        return Term.get_current_week()

    if request.user.is_authenticated:
        semester = current_term()
        if semester is None:
            return redirect(reverse_lazy('school:manage_semester', kwargs={'school_id':request.user.school.id}))
        else:
            if request.user.user_type is User.HOMEROOM:
                return redirect(reverse_lazy('timetable:home_view', kwargs={'user_id':request.user.id, 'semester_id':current_term().pk, 'start':current_week()[0]}))
            elif request.user.user_type is User.SUBJECT:
                return redirect(reverse_lazy('timetable:sub_view', kwargs={'user_id':request.user.id, 'semester_id':current_term().pk, 'start':current_week()[0]}))
            elif request.user.user_type is User.INVITED:
                semester = current_term()
                if semester is None:
                    week = current_week()
                else:
                    week = semester.get_week(InvitedTeacher.get_from(request.user).start)
                return redirect(reverse_lazy('timetable:inv_view', kwargs={'user_id':request.user.id, 'semester_id':current_term().pk, 'start':week[0]}))
    else:
        return redirect(reverse_lazy('account:login'))

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('account/', include('accounts.urls')),
    path('school/', include('school.urls')),
    path('timetable/', include('timetable.urls')),
]

school/urls.py
'''
School Information managemenet urls
'''
from django.urls import path
from . import views

app_name = 'school'

urlpatterns = [
    path('school/', views.SchoolSignUp.as_view(), name='school_signup'),
    path('<int:school_id>/manage/term', views.TermManageListView.as_view(), name='manage_semester'),
    path('<int:school_id>/manage/subject', views.SubjectManageListView.as_view(), name='manage_subject'),
    path('<int:school_id>/manage/classroom', views.ClassRoomManageListView.as_view(), name='manage_classroom'),

    path('<int:school_id>/filter_by_grade_cla/', views.ClassRoomGradeFilterView.as_view(), name='filter_classroom'),
    path('<int:school_id>/filter_by_grade_sub/', views.SubjectGradeFilterView.as_view(), name='filter_subject'),

    path('semesters/', views.semesters, name='semesters'),
    path('<int:school_id>/create_semester/', views.SemesterCreateView.as_view(), name='create_semester'),
    path('<int:school_id>/update_semester/<int:pk>', views.SemesterUpdateView.as_view(), name='update_semester'),
    path('<int:school_id>/delete_semester/<int:pk>', views.SemesterDeleteView.as_view(), name='delete_semester'),

    path('holidays/', views.holidays, name='holidays'),
    path('<int:school_id>/create_holiday/', views.HolidayCreateView.as_view(), name='create_holiday'),
    path('<int:school_id>/update_holiday/<int:pk>', views.HolidayUpdateView.as_view(), name='update_holiday'),
    path('<int:school_id>/delete_holiday/<int:pk>', views.HolidayDeleteView.as_view(), name='delete_holiday'),

    path('classrooms/', views.classrooms, name='classrooms'),
    path('<int:school_id>/create_classroom/', views.ClassRoomCreateView.as_view(), name='create_classroom'),
    path('<int:school_id>/update_classroom/<int:pk>', views.ClassRoomUpdateView.as_view(), name='update_classroom'),
    path('<int:school_id>/delete_classroom/<int:pk>', views.ClassRoomDeleteView.as_view(), name='delete_classroom'),

    path('subjects/', views.subjects, name='subjects'),
    path('<int:semester_id>/create_subject/', views.SubjectCreateView.as_view(), name='create_subject'),
    path('<int:semester_id>/update_subject/<int:pk>', views.SubjectUpdateView.as_view(), name='update_subject'),
    path('<int:semester_id>/delete_subject/<int:pk>', views.SubjectDeleteView.as_view(), name='delete_subject'),
]

timetable/urls.py
'''
modul doc
'''
from django.urls import path, register_converter
from . import converters, views

register_converter(converters.DateConverter, 'date')

app_name = 'timetable'

urlpatterns = [
    path('<int:user_id>/<int:semester_id>/sub/create/', views.SubjectCreate.as_view(), name='sub_create'),
    path('<int:user_id>/<int:semester_id>/sub/reset/', views.SubjectReset.as_view(), name='sub_reset'),
    path('<int:user_id>/<int:semester_id>/<date:start>/sub/view/', views.SubjectView.as_view(), name='sub_view'),
    path('<int:user_id>/<int:semester_id>/<date:start>/sub/update/', views.SubjectUpdate.as_view(), name='sub_update'),

    path('<int:user_id>/<int:semester_id>/home/create/', views.HomeroomCreate.as_view(), name='home_create'),
    path('<int:user_id>/<int:semester_id>/home/reset/', views.HomeroomReset.as_view(), name='home_reset'),
    path('<int:user_id>/<int:semester_id>/<date:start>/home/view/', views.HomeroomView.as_view(), name='home_view'),
    path('<int:user_id>/<int:semester_id>/<date:start>/home/update/', views.HomeroomUpdate.as_view(), name='home_update'),

    path('<int:user_id>/<int:semester_id>/inv/create/', views.InvitedCreate.as_view(), name='inv_create'),
    path('<int:user_id>/<int:semester_id>/inv/reset/', views.InvitedReset.as_view(), name='inv_reset'),
    path('<int:user_id>/<int:semester_id>/<date:start>/inv/view/', views.InvitedView.as_view(), name='inv_view'),
    path('<int:user_id>/<int:semester_id>/<date:start>/inv/update/', views.InvitedUpdate.as_view(), name='inv_update'),
]

timetable/views.py
"""
module doc
"""
from django.utils import timezone
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib import messages
from django.shortcuts import redirect
from django.views import generic
from django.urls import reverse_lazy
from bootstrap_modal_forms.generic import BSModalFormView
from school.models import Term, Subject, ClassRoom
from .models import SubjectTable, HomeTable, Invited
from .forms import TableCreateForm
from .forms import (SubjectTableForm, HomeTableForm, InvitedTableForm, SubjectTableUpdateFormset, HomeTableUpdateFormset, InvitedTableUpdateFormset)
from .utils import create_list_for_weeks
##########################################################
### Teacher Roles == Subject Features
class SubjectCreate(LoginRequiredMixin, BSModalFormView):
    '''
    class doc
    '''
    form_class = TableCreateForm
    template_name = 'create.html'

    # added member
    def get_semester(self):
        qs = Term.objects.filter(pk=self.kwargs['semester_id']) # in url
        if qs:
            return qs.get()
        return None

    def form_valid(self, form):
        if self.request.is_ajax(): #bug django-bootstrap-modal-forms twice redirection
            semester = form.cleaned_data['semester']
            week = semester.get_week()
            weeks = semester.get_count_of_weeks()
            bulk_tables = []
            for i in range(0, weeks+1):
                for j in range(0, 40):
                    new_table = SubjectTable(teacher=self.request.user, semester=semester, day=week[j%5] + timezone.timedelta(days=7*i), time=(j//5)%8+1)
                    bulk_tables.append(new_table)
            SubjectTable.objects.bulk_create(bulk_tables)
        return redirect(self.get_success_url())

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

    def get_success_url(self):
        week = Term.get_current_week()
        return reverse_lazy('timetable:sub_view', kwargs={'user_id':self.request.user.id, 'semester_id':self.get_semester().pk, 'start':week[0]})

class SubjectUpdate(LoginRequiredMixin, generic.UpdateView):
    '''
    class doc
    '''
    template_name = 'sub/update.html'
    model = SubjectTable
    form_class = SubjectTableForm

    # added member
    def get_semester(self):
        qs = Term.objects.filter()
        if qs:
            return qs.get()
        return None

    def create_list_for_weeks(self):
        return create_list_for_weeks(self.get_semester())

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse_lazy('timetable:sub_view', kwargs={'user_id':self.request.user.id, 'semester_id':self.kwargs['semester_id'], 'start':self.kwargs['start']})

    def get_context_data(self, **kwargs):
        context = super(SubjectUpdate, self).get_context_data(**kwargs)
        start = self.kwargs['start']
        end = start + timezone.timedelta(days=4)
        qs = SubjectTable.objects.filter(semester=self.get_semester(), teacher=self.request.user, day__range=(start, end)).order_by("time", "day")
        if self.request.POST:
            context['timetables'] = SubjectTableUpdateFormset(self.request.POST, instance=self.request.user, queryset=qs)
        else:
            context['timetables'] = SubjectTableUpdateFormset(instance=self.request.user, queryset=qs)
        context['list_weeks'] = self.create_list_for_weeks()
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['timetables']
        if formset.is_valid():
            weeks = []
            for week in context['list_weeks']:
                if self.request.POST.get(f"{week['day'].strftime('%W')}week") is not None:
                    weeks.append(self.request.POST.get(f"{week['day'].strftime('%W')}week"))
            for form in formset:
                inst = form.save(commit=False)
                qs = SubjectTable.objects.filter(semester=Term.get_current(), teacher=self.request.user, day__iso_week_day=inst.day.isoweekday(), day__week__in=weeks, time=inst.time)
                for ins in qs:
                    ins.subject = inst.subject
                    ins.classroom = inst.classroom
                    ins.save()
            return redirect(self.get_success_url())
        else:
            return self.render_to_response(self.get_context_data(form=form))

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

class SubjectReset(LoginRequiredMixin, BSModalFormView):
    form_class = TableCreateForm
    template_name = 'reset.html'

    def form_valid(self, form):
        if self.request.is_ajax(): #bug django-bootstrap-modal-forms twice redirection
            semester = form.cleaned_data['semester']
            sub = SubjectTable.objects.filter(teacher=self.request.user, semester=semester)
            HomeTable.objects.filter(sub_teacher__in=sub).update(subject=None, sub_teacher=None)
            sub.update(classroom=None, subject=None)
        return redirect(self.get_success_url())

    def get_success_url(self):
        week = Term.get_current_week()
        return reverse_lazy('timetable:sub_view', kwargs={'user_id':self.request.user.id, 'semester_id':self.kwargs['semester_id'], 'start':week[0]})

class SubjectView(LoginRequiredMixin, generic.TemplateView):
    '''
    class doc
    '''
    template_name = 'sub/view.html'
    model = SubjectTable

    # added member
    def get_semester(self):
        qs = Term.objects.filter()
        if qs:
            return qs.get()
        return None

    def get_week(self):
        start = self.kwargs['start']
        end = start + timezone.timedelta(days=4)
        return {'start':self.kwargs['start'], 'end':end}

    def create_list_for_weeks(self):
        return create_list_for_weeks(self.get_semester())

    def create_information(self):
        '''
        Return TimeTable information to Templates
        '''
        information = dict()
        semester = self.get_semester()
        if semester is None:
            return
        weeks = semester.get_weeks_start_end()
        classrooms = SubjectTable.objects.exclude(classroom=None).distinct('classroom').values_list('classroom', flat=True).order_by()

        for classroom in classrooms:
            count_per_week = []
            for week in weeks:
                count_per_week.append(SubjectTable.objects.filter(semester=self.get_semester(), teacher=self.request.user, classroom=classroom, day__range=(week[0].strftime("%Y-%m-%d"), week[1].strftime("%Y-%m-%d"))).count())
            dic = {ClassRoom.objects.get(pk=classroom):[count_per_week, SubjectTable.objects.filter(teacher=self.request.user, classroom=classroom).count()]}

            information.update(dic)
        return information

    def get_success_url(self):
        '''
        class doc
        '''
        return redirect('timetable:sub_view')

    def get_context_data(self, **kwargs):
        context = super(SubjectView, self).get_context_data(**kwargs)
        start = self.kwargs['start']
        end = start + timezone.timedelta(days=4)
        context['timetables'] = SubjectTable.objects.filter(semester=self.get_semester(), teacher=self.request.user, day__range=(start, end)).order_by("time", "day")
        context['list_weeks'] = self.create_list_for_weeks()
        context['information'] = self.create_information()
        return context

### the end of subject
##########################################################
### Teacher Roles == Homeroom Features
class HomeroomCreate(LoginRequiredMixin, BSModalFormView):
    form_class = TableCreateForm
    template_name = 'create.html'

    # added member
    def get_semester(self):
        qs = Term.objects.filter(pk=self.kwargs['semester_id']) # in url
        if qs:
            return qs.get()
        return None

    def form_valid(self, form):
        if self.request.is_ajax(): #bug django-bootstrap-modal-forms twice redirection
            semester = form.cleaned_data['semester']
            week = semester.get_week()
            weeks = semester.get_count_of_weeks()
            bulk_tables = []
            for i in range(0, weeks+1):
                for j in range(0, 40):
                    classroom = self.request.user.return_by_type().classroom
                    new_table = HomeTable(semester=semester, teacher=self.request.user, classroom=classroom, day=week[j%5]+timezone.timedelta(days=7*i), time=(j//5)%8+1)
                    bulk_tables.append(new_table)
            HomeTable.objects.bulk_create(bulk_tables)
        return redirect(self.get_success_url())

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

    def get_success_url(self):
        week = Term.get_current_week()
        return reverse_lazy('timetable:home_view', kwargs={'user_id':self.request.user.id, 'semester_id':self.get_semester().pk, 'start':week[0]})

class HomeroomUpdate(LoginRequiredMixin, generic.UpdateView):
    '''
    class doc
    '''
    template_name = 'home/update.html'
    model = HomeTable
    form_class = HomeTableForm

    # added member
    def get_semester(self):
        qs = Term.objects.filter()
        if qs:
            return qs.get()
        return None

    def create_list_for_weeks(self):
        return create_list_for_weeks(self.get_semester())

    def auto_created_subject(self):
        from operator import itemgetter
        # picking algorithm
        sub_lis = []
        subjects = Subject.objects.filter(grade=self.request.user.return_by_type().get_grade())
        for subject in subjects:
            cur = HomeTable.objects.filter(subject=subject).count()
            tot = subject.count
            # caculate key value
            key = cur/tot
            sub_lis.append((key, subject))

timetable/templates/inv/_list.html
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
  <div class="sidebar-sticky">
    <ul class="nav flex-column">
    {% if object %}
      {% for week in list_weeks %}
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.kwargs.start == week.day %}active{% endif %}" href="{% url 'timetable:inv_update' user.id week.pk week.day %}">
          <input class="list-week" type="checkbox" name="{{ week.day|date:'W' }}week" value="{{ week.day|date:'W' }}" {% if request.resolver_match.kwargs.start == week.day %}checked{% endif %}>
          {{ week.day | date:"W" }} 주차 ({{ week.day|date:"m/d" }})
        </a>
      </li>
      {% endfor %}
      <li class="nav-item">
        <a class="nav-link">
          <input id='select-all' type="checkbox">
          All
        </a>
      </li>
    {% else %}
      {% for week in list_weeks %}
      <li class="nav-item">
        <a class="nav-link {% if request.resolver_match.kwargs.start == week.day %}active{% endif %}" href="{% url 'timetable:inv_view' user.id week.pk week.day %}">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-file-text"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path><polyline points="14 2 14 8 20 8"></polyline><line x1="16" y1="13" x2="8" y2="13"></line><line x1="16" y1="17" x2="8" y2="17"></line><polyline points="10 9 9 9 8 9"></polyline></svg>
          {{ week.day | date:"W" }} 주차 ({{ week.day|date:"m/d" }})
        </a>
      </li>
      {% endfor %}
    {% endif %}
    </ul>
  </div>
</nav>

timetable/templates/inv/update.html
{% extends 'base.html' %}

{% block extrascripts %}
<script type="text/javascript">
    $(function () {
      $('#select-all').change(function () {
        if ($(this).prop('checked')) {
            $('.list-week').prop('checked', true);
        } else {
            $('.list-week').prop('checked', false);
        }
      });
    })
</script>
{% endblock extrascripts %}

{% load widget_tweaks %}

{% load static %}
{% block content %}

  <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
      <h1 class="h2">Invited </h1>
      <button class="btn btn btn-outline-secondary" data-provide="datepicker" id="weekpicker" disabled>
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
        {{ request.resolver_match.kwargs.start|date:"Y/m/d" }} ~
      </button>
    </div>

    <form action="" method="post">
    <div class="table-responsive">
        <table class="table table-bordered table-hover" id="TimeTableUpdate">
          <thead class="">
            <th scope="col" style="width: 2.5%" >#</th> 
            <th scope="col" style="width: 12.5%">Mon</th>
            <th scope="col" style="width: 12.5%">Tue</th>
            <th scope="col" style="width: 12.5%">Wed</th>
            <th scope="col" style="width: 12.5%">Thr</th>
            <th scope="col" style="width: 12.5%">Fri</th>
        </thead>
        <tbody>
        {% csrf_token %}
        {% for course in timetables %}
        {% cycle '<tr scope="row"><th></th>' '' '' '' '' %}
          <td> 
            {% for field in course %}
            <div class="form-group">
              {% render_field field class="form-control" placeholder=field.label %}
              <div class="{% if field.errors %} invalid {% endif %}">
                {% for error in field.errors %}
                  <p class="help-block">{{ error }}</p>
                {% endfor %}
              </div>
            </div>
            {% endfor %}
          </td>
        {% cycle '' '' '' '' '</tr>' %}
        {% endfor %}
        </tbody>
      </table>

      <div class="modal-footer">
        <button type="submit" class="btn btn-secondary btn-lg">Update</button>
      </div>
      {{ timetables.management_form }}
      {{ timetables.non_form_errors.as_ul }}
    </div>

    {% if list_weeks %}
    {% include 'inv/_list.html' %}
    {% endif %}
    </form>
  </main>
{% endblock content %}

timetable/templates/inv/view.html
{% extends 'base.html' %}

{% block extrascripts %}
<script type="text/javascript">
    $(function () {
      $("#inv-create").modalForm({
        formURL: "{% url 'timetable:inv_create' user.id semester_id %}"
      });
      $("#inv-reset").modalForm({
        formURL: "{% url 'timetable:inv_reset' user.id semester_id %}"
      });
      })

</script>
{% endblock extrascripts %}

{% load static %}
{% block content %}
{% include "_modal.html" %}

  {% if list_weeks %}
  {% include 'inv/_list.html' %}
  {% endif %}

  <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Invited</h1>
    <button class="btn btn-sm btn-outline-secondary" data-provide="datepicker" id="weekpicker" disabled>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-calendar"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
      {{ request.resolver_match.kwargs.start|date:"Y/m/d" }} ~ {{ timetables.4.day|date:"Y/m/d" }}
    </button>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group mr-2">
        <a class="btn btn-sm btn-outline-secondary" id="inv-create">
          Create
        </a>
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'timetable:inv_update' user.id semester_id start %}">
          Update
        </a>
        <a class="btn btn-sm btn-outline-secondary" id="inv-reset">
          Reset
        </a>
      </div>
    </div>
  </div>

  <div class="table-responsive">

    <form action="" method="get" id="Table-View-form">
      {% csrf_token %}
      <table class="table table-bordered table-hover" id="TimeTableView">
        <thead class="">
          <th scope="col" style="width: 12.5%">{{ timetables.0.day|date:"D m/d" }}</th>
          <th scope="col" style="width: 12.5%">{{ timetables.1.day|date:"D m/d" }}</th>
          <th scope="col" style="width: 12.5%">{{ timetables.2.day|date:"D m/d" }}</th>
          <th scope="col" style="width: 12.5%">{{ timetables.3.day|date:"D m/d" }}</th>
          <th scope="col" style="width: 12.5%">{{ timetables.4.day|date:"D m/d" }}</th>
        </thead>
        <tbody>
        {% for course in timetables %}
        {% cycle '<tr scope="row" style="height: 100px;">' '' '' '' ''%}
          <td class="text-center">
              <div class="col"> 
                <p>{% if course.classroom %}{{ course.classroom }}{% endif %}</p>
                <p>{% if course.subject %}{{ course.subject }}{% endif %}</p>
            </div>
          </td>
        {% cycle '' '' '' '' '</tr>' %}
        {% endfor %}
        </tbody>
        </table>
      {{ timetables.management_form }}
      {{ timetables.non_form_errors.as_ul }} 
    </form>
    </div>
    {% if information %}
      {% include '_info.html' %}
    {% endif %}
  </main>

{% if count %}
  {% include '_count.html' %}
{% endif %}

{% endblock %}